version: "3.8"
services:
  server-engine:
    build: ./
    container_name: server-engine-q
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
